version: 43.0.9
pageUuid: b6a12cb0-bc74-11ed-a336-f7fea3edbc78
appTemplate:
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.113.1
  markdownLinkBehavior: auto
