version: 43.0.9
pageUuid: fa173d20-d314-11ed-9ff0-0bb7838f0cdd
appTemplate:
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  rootScreen: null
  version: 2.117.0
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
