version: 43.0.9
pageUuid: 1ad25144-f9ad-11ed-91fd-23ca8e405560
appTemplate:
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  rootScreen: null
  version: 2.123.0
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
