version: 43.0.9
pageUuid: 06d31142-ca8c-11ed-8b97-e7c48dc89d7a
appTemplate:
  folders:
    - folder1
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  version: 2.117.1
  experimentalDataTabEnabled: true
