<PlaygroundQuery
  id="_Momentic query test 1712876732196"
  adhocResourceType="RESTQuery"
  data={null}
  resourceType={null}
>
  <RESTQuery
    allowedGroupIds={[]}
    allowedGroups={[]}
    events={[]}
    importedQueryDefaults={{}}
    importedQueryInputs={{}}
    privateParams={[]}
    query="https://dummyjson.com/products/1"
    queryTimeout="100000"
    retoolVersion="3.45.0"
    watchedParams={[]}
  />
</PlaygroundQuery>
