version: 43.0.9
pageUuid: 03d1f7f2-aa42-11ed-936c-271e4ace3fbc
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
      mobileOfflineModeDelaySync: false
  queryStatusVisibility: false
  rootScreen: null
  version: 2.111.0
  markdownLinkBehavior: auto
