<PlaygroundQuery
  id="_Momentic query test 1712853589088"
  adhocResourceType="RESTQuery"
  data={null}
  resourceType={null}
>
  <RESTQuery
    allowedGroupIds={[]}
    allowedGroups={[]}
    events={[]}
    importedQueryDefaults={{}}
    importedQueryInputs={{}}
    privateParams={[]}
    query="https://jsonplaceholder.typicode.com/todos/1"
    queryTimeout="100000"
    retoolVersion="3.44.0"
    watchedParams={[]}
  />
</PlaygroundQuery>
