version: 43.0.9
pageUuid: 9ab4ce76-bc74-11ed-ad9b-ffd123e548d6
appTemplate:
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  rootScreen: null
  version: 2.116.0
  markdownLinkBehavior: auto
