version: 43.0.9
pageUuid: 74c76cb4-ad7e-11ed-969f-b3c5869a6467
appTemplate:
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  rootScreen: null
  version: 2.115.0
  markdownLinkBehavior: auto
