version: 43.0.9
pageUuid: d25a057a-fee8-11ec-9cc7-375217ae72b1
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  version: 2.95.2
  markdownLinkBehavior: auto
