version: 43.0.9
pageUuid: 4ba4ced2-75c8-11ed-a66a-fbf1c1251fc1
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
  queryStatusVisibility: false
  rootScreen: null
  version: 2.108.0
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
