name: Deploy Workflow

on:
  pull_request:
    branches: [ main ]  # Trigger the workflow on pull requests targeting the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Commit
        run: |
          export COMMIT_SHA=$GITHUB_SHA
          echo "Deploying commit SHA $COMMIT_SHA on https://a02e-50-217-234-18.ngrok-free.app/api/v2/source_control/test_deploy"
          response=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.RETOOL_DRY_DEPLOY_API_KEY }}" -d "{\"deployParams\": {\"commit_sha\": \"$COMMIT_SHA\"}}" https://a02e-50-217-234-18.ngrok-free.app/api/v2/source_control/test_deploy)
          echo "API Response:"
          echo "$response"
          if [[ $(echo $response | jq '.data.success') != "true" ]]; then
            echo "Test failed"
            exit 1
          fi
