version: 43.0.9
pageUuid: 6da65204-c121-11ed-9aa3-bb2823aa006b
appTemplate:
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  rootScreen: null
  version: 2.115.0
  markdownLinkBehavior: auto
